version: "2"
services:
  tests:
    build: .
    image: keboola/google-sheets-client
    working_dir: /code
    command: composer ci
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - REFRESH_TOKEN
      - GOOGLE_DRIVE_FOLDER
      - GOOGLE_DRIVE_TEAM_FOLDER

  dev:
    build: .
    image: keboola/google-sheets-client
    volumes:
      - .:/code
    working_dir: /code
    command: composer ci
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - REFRESH_TOKEN
      - GOOGLE_DRIVE_FOLDER
      - GOOGLE_DRIVE_TEAM_FOLDER
